rstaurant:
    resource: "@RstaurantBundle/Resources/config/routing.yml"
    #prefix:   /restaurant/
    prefix:   /



app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /restaurant/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /restaurant/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /restaurant/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /restaurant/profile
#REST
rest :
  type : rest
  resource : "@RstaurantBundle/Resources/config/routing_rest.yml"
  prefix : /api
