rstaurant_homepage:
    path:     /
    defaults: { _controller: RstaurantBundle:Default:index }

admin_dashboard:
    path:     /dashboard
    defaults: { _controller: RstaurantBundle:Admin:index }

restaurant_dashboard:
    path:     /restaurant
    defaults: { _controller: RstaurantBundle:Restaurant:index }
user_dashboard:
    path:     /user
    defaults: { _controller: RstaurantBundle:Default:index }

admin_form:
    path:     /form
    defaults: { _controller: RstaurantBundle:Example:new }
